# Generated by Django 3.2.9 on 2021-11-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='姓')),
                ('last_name', models.CharField(max_length=20, verbose_name='名')),
                ('mail', models.CharField(default='', max_length=20, verbose_name='邮箱')),
                ('peopleID', models.CharField(max_length=20, verbose_name='ID')),
                ('Authorizate', models.CharField(choices=[('管理员', '管理员'), ('网站管理员', '网站管理员'), ('超级管理员', '超级管理员'), ('骨干成员', '骨干成员'), ('普通人员', '普通人员'), ('访客', '访客'), ('黑名单', '黑名单')], default='骨干成员', max_length=16)),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
