# Generated by Django 3.2.9 on 2021-11-11 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PMS', '0001_initial'),
        ('RMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit_Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KitBoard_ID', models.CharField(default=81, max_length=20, verbose_name='开发板ID')),
                ('KitBoard_type', models.CharField(default='', max_length=20, verbose_name='开发板型号')),
                ('Price', models.FloatField(default=0, verbose_name='价格')),
                ('Pub_time', models.DateField(auto_now=True, verbose_name='购买时间')),
                ('Status', models.CharField(choices=[('正常', '正常'), ('借出', '借出'), ('审核中', '审核中'), ('报废', '报废')], default='正常', max_length=20, verbose_name='开发板状态')),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.person')),
                ('Receipt_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RMS.receipt')),
            ],
            options={
                'verbose_name': '开发板',
                'verbose_name_plural': '开发板',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
