# Generated by Django 3.2.9 on 2021-11-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_ID', models.CharField(max_length=20)),
                ('Input_time', models.DateField(default='')),
                ('Status', models.CharField(choices=[('正常', '正常'), ('借出', '借出'), ('审核中', '审核中'), ('报废', '报废')], max_length=20)),
            ],
            options={
                'verbose_name': '设备管理',
                'verbose_name_plural': '设备管理',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
