# Generated by Django 3.2.9 on 2021-11-11 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buy_time', models.DateField()),
                ('Type', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('Quantity_call', models.IntegerField()),
                ('Receipt_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RMS.receipt')),
            ],
            options={
                'verbose_name': '耗材',
                'verbose_name_plural': '耗材',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
